library(data.table)
hpc <- fread("household_power_consumption.txt", na.strings = "?",data.table=FALSE)
hpc <- subset(hpc, Date == "1/2/2007"|Date == "2/2/2007")
hpc$Time <- strptime(paste0(hpc$Date,hpc$Time),"%d/%m/%Y %H:%M:%S")
hpc$Date <- as.Date(hpc$Date,"%d/%m/%Y")

with(hpc, plot(Time,Sub_metering_1, ylab = "Energy Sub Metering", xlab="",type="n"))
with(hpc, lines(Time,Sub_metering_1))
with(hpc, lines(Time,Sub_metering_2, col ="red"))
with(hpc, lines(Time,Sub_metering_3, col = "blue"))
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty = c(1,1,1),col=c("black","red","blue"))
dev.copy(png, file = "plot3.png", width = 480, height = 480)
dev.off()